# Generated by Django 2.0.7 on 2018-07-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp',
            old_name='username',
            new_name='user',
        ),
    ]
