# Generated by Django 2.0.7 on 2018-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180712_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
