# Generated by Django 2.0.7 on 2018-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20180718_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp',
            name='boss',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
